services:
  igniscore:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: igniscore
    restart: unless-stopped

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

    networks:
      - compose_default

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.igniscore.rule=Host(`igniscore.com.br`)"
      - "traefik.http.routers.igniscore.entrypoints=websecure"

      - "traefik.http.routers.igniscore.tls=true"
      - "traefik.http.routers.igniscore.tls.certresolver=le"

      - "traefik.http.services.igniscore.loadbalancer.server.port=8080"

networks:
  compose_default:
    external: true
