spring:
  application:
    name: igniscore

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update

  graphql:
    graphiql:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  security:
    token:
      secret: ${JWT_SECRET}
